# Generated by Django 5.2.4 on 2025-08-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('S', 'shipped'), ('D', 'delivered')], default='P', max_length=1),
        ),
    ]
