# Generated by Django 5.2.4 on 2025-08-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
