# Generated by Django 5.2.4 on 2025-08-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_userprofile_cart_delete_productbackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cart',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
