# Generated by Django 5.2.4 on 2025-08-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
